<?php
/**
 * Implements hook_default_search_api_server().
 */
function unfi_search_settings_default_search_api_server() {
  $items = array();

  $host = variable_get('solr_search_api_host', 'localhost');
  $port = variable_get('solr_search_api_port', '8983');
  $path = variable_get('solr_search_api_path', '\\/solr');
  $scheme = variable_get('solr_search_api_scheme', 'http');

  $items['solr'] = entity_import('search_api_server', '{
    "name" : "Solr server",
    "machine_name" : "solr",
    "description" : "",
    "class" : "search_api_solr_service",
    "options" : {
      "host" : "' . $host . '",
      "port" : "' . $port . '",
      "path" : "' . $path . '",
      "http_user" : "",
      "http_pass" : "",
      "excerpt" : 1,
      "retrieve_data" : 1,
      "highlight_data" : 0,
      "scheme" : "' . $scheme . '"
    },
    "enabled" : "1",
    "rdf_mapping" : []
  }');

  return $items;
}
