<?php

/**
 * Implements hook_menu().
 *
 */
function bluemarble_image_serve_menu() {
 $items = array();

  // Create an administration block for the module and any submodules.
  $items['service/digitalcore/products/image/%'] = array(
    'page callback' => 'bluemarble_image_serve_get_image',
    'access arguments' => array('view files'),
    'page arguments' => array(4),
    'access callback' => 'user_access',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/*
 * retrieve the image file associated with the upc provided
 */
function bluemarble_image_serve_get_image($upc) {
  $cid = 'digital_core_image:' . $upc;

  $url = FALSE;

  $cache = cache_get($cid);
  if ($cache) {
    $url = $cache->data;
  }
  else {
    module_load_include('inc', 'bluemarble_data', 'bluemarble_data_products');
    $product = bluemarble_data_products_read(array("search" => $upc), array("field_item_num"));

    if($product['count'] > 0) {
      $product = array_shift($product['results']);

      $pathinfo = pathinfo($product['thumb_url']);

      if ($pathinfo['filename'] != "default_image") {
        $url = $product['thumb_url'];
        cache_set($cid, $url);
      }
    }
  }

  if ($url) {
    header('Location: ' . $url);
    exit();
  }

  // No url, cache that the image was not found for an hour to reduce upc lookups.
  cache_set($cid, FALSE, 'cache', REQUEST_TIME + 3600);
  http_response_code(404);
  exit();
}